In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [27]:
df = pd.read_csv('https://bit.ly/HDSC-StageOneDataset')
df

,record_id,utility_id_ferc1,report_year,plant_name_ferc1,fuel_type_code_pudl,fuel_unit,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
0,f1_fuel_1994_12_1_0_7,1,1994,rockport,coal,ton,5377489.0,16.590,18.59,18.53,1.121
1,f1_fuel_1994_12_1_0_10,1,1994,rockport total plant,coal,ton,10486945.0,16.592,18.58,18.53,1.120
2,f1_fuel_1994_12_2_0_1,2,1994,gorgas,coal,ton,2978683.0,24.130,39.72,38.12,1.650
3,f1_fuel_1994_12_2_0_7,2,1994,barry,coal,ton,3739484.0,23.950,47.21,45.99,1.970
4,f1_fuel_1994_12_2_0_10,2,1994,chickasaw,gas,mcf,40533.0,1.000,2.77,2.77,2.570
...,...,...,...,...,...,...,...,...,...,...,...
29518,f1_fuel_2018_12_12_0_13,12,2018,neil simpson ct #1,gas,mcf,18799.0,1.059,4.78,4.78,9.030
29519,f1_fuel_2018_12_12_1_1,12,2018,cheyenne prairie 58%,gas,mcf,806730.0,1.050,3.65,3.65,6.950
29520,f1_fuel_2018_12_12_1_10,12,2018,lange ct facility,gas,mcf,104554.0,1.060,4.77,4.77,8.990
29521,f1_fuel_2018_12_12_1_13,12,2018,wygen 3 bhp 52%,coal,ton,315945.0,16.108,3.06,14.76,1.110
29522,f1_fuel_2018_12_12_1_14,12,2018,wygen 3 bhp 52%,gas,mcf,17853.0,1.059,0.00,0.00,11.680

In [28]:
df.describe()

,utility_id_ferc1,report_year,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
count,29523.000000,29523.000000,2.952300e+04,29523.000000,29523.000000,2.952300e+04,29523.000000
mean,118.601836,2005.806050,2.622119e+06,8.492111,208.649031,9.175704e+02,19.304354
std,74.178353,7.025483,9.118004e+06,10.600220,2854.490090,6.877593e+04,2091.540939
min,1.000000,1994.000000,1.000000e+00,0.000001,-276.080000,-8.749370e+02,-41.501000
25%,55.000000,2000.000000,1.381700e+04,1.024000,5.207000,3.778500e+00,1.940000
50%,122.000000,2006.000000,2.533220e+05,5.762694,26.000000,1.737100e+01,4.127000
75%,176.000000,2012.000000,1.424034e+06,17.006000,47.113000,4.213700e+01,7.745000
max,514.000000,2018.000000,5.558942e+08,341.260000,139358.000000,7.964521e+06,359278.000000

In [93]:
A = [1,2,3,4,5,6]
B = [13, 21, 34]

In [94]:
A_B = A+B
A_B

[1, 2, 3, 4, 5, 6, 13, 21, 34]

In [37]:
df['fuel_mmbtu_per_unit'].std()

10.600220307806886

In [41]:
df['fuel_qty_burned'].skew()

15.851495469109503

In [40]:
df['fuel_qty_burned'].kurt()

651.3694501337732

In [98]:
df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].min()

fuel_type_code_pudl
coal         0.00
gas          0.00
nuclear      0.00
oil          0.00
other     -119.04
waste     -276.08
Name: fuel_cost_per_unit_burned, dtype: float64

In [97]:
df.groupby('report_year')['fuel_cost_per_unit_burned'].max()

report_year
1994     44009.190
1995     62609.000
1996     33150.000
1997     48164.000
1998     54376.000
1999     31640.600
2000     51698.000
2001     34652.000
2002     35486.000
2003     34518.000
2004     31825.840
2005     35948.000
2006     43851.000
2007     45486.000
2008     45578.820
2009     49650.832
2010     64313.100
2011     83538.000
2012     65137.588
2013     61717.765
2014    139358.000
2015     53889.540
2016     55098.539
2017     51417.892
2018     44738.780
Name: fuel_cost_per_unit_burned, dtype: float64

In [99]:
bom = df.groupby('report_year').describe()
bom

            utility_id_ferc1                                                   \
                       count        mean        std  min    25%    50%    75%
report_year
1994                  1235.0  106.120648  61.637376  1.0  49.00  115.0  161.0
1995                  1201.0  110.139051  62.848480  1.0  55.00  121.0  163.0
1996                  1088.0  108.714154  62.481365  1.0  51.00  120.0  163.0
1997                  1094.0  108.366545  60.362734  1.0  56.00  119.0  161.0
1998                  1107.0  109.845528  60.583260  1.0  56.00  120.0  161.0
1999                  1050.0  108.222857  61.968732  1.0  55.00  119.0  163.0
2000                  1373.0  111.083758  66.152352  1.0  51.00  120.0  164.0
2001                  1356.0  113.521386  68.832136  1.0  55.00  119.5  173.0
2002                  1205.0  120.354357  75.108768  1.0  55.00  122.0  182.0
2003                  1211.0  123.300578  75.600574  1.0  55.50  127.0  186.0
2004                  1192.0  121.123322  72.512675  1.0  56.00  127.0  182.0
2005                  1269.0  121.028369  75.085698  1.0  55.00  127.0  186.0
2006                  1243.0  117.178600  72.869473  1.0  55.00  121.0  182.0
2007                  1264.0  116.040348  72.882279  1.0  51.00  120.0  182.0
2008                  1228.0  120.785016  75.709915  1.0  56.00  127.0  183.0
2009                  1222.0  118.139116  76.871807  1.0  51.00  121.0  177.0
2010                  1261.0  117.992863  75.684427  1.0  51.00  121.0  177.0
2011                  1240.0  121.069355  76.110461  1.0  55.75  127.0  177.0
2012                  1243.0  120.769912  75.054656  1.0  55.00  127.0  177.0
2013                  1199.0  122.082569  72.650126  1.0  56.00  127.0  182.0
2014                  1171.0  129.263877  89.646521  1.0  56.00  132.0  182.0
2015                  1093.0  128.591949  83.920139  1.0  57.00  134.0  182.0
2016                  1034.0  133.117021  87.970166  1.0  57.00  134.0  186.0
2017                   993.0  131.126888  87.791301  1.0  56.00  134.0  182.0
2018                   951.0  133.669821  88.412742  1.0  57.50  134.0  186.0

                   fuel_qty_burned                ...  \
               max           count          mean  ...
report_year                                       ...
1994         208.0          1235.0  2.724018e+06  ...
1995         213.0          1201.0  3.712067e+06  ...
1996         230.0          1088.0  2.544754e+06  ...
1997         213.0          1094.0  2.813503e+06  ...
1998         230.0          1107.0  3.267453e+06  ...
1999         244.0          1050.0  3.281281e+06  ...
2000         270.0          1373.0  2.472032e+06  ...
2001         276.0          1356.0  2.321402e+06  ...
2002         285.0          1205.0  2.145645e+06  ...
2003         287.0          1211.0  1.888622e+06  ...
2004         294.0          1192.0  1.782547e+06  ...
2005         294.0          1269.0  1.768876e+06  ...
2006         294.0          1243.0  1.957264e+06  ...
2007         294.0          1264.0  2.035696e+06  ...
2008         432.0          1228.0  2.046455e+06  ...
2009         432.0          1222.0  2.154993e+06  ...
2010         432.0          1261.0  2.423720e+06  ...
2011         449.0          1240.0  2.461332e+06  ...
2012         449.0          1243.0  2.747094e+06  ...
2013         449.0          1199.0  2.741505e+06  ...
2014         452.0          1171.0  2.700008e+06  ...
2015         454.0          1093.0  3.340131e+06  ...
2016         513.0          1034.0  3.693289e+06  ...
2017         514.0           993.0  3.352850e+06  ...
2018         514.0           951.0  4.178890e+06  ...

            fuel_cost_per_unit_delivered              fuel_cost_per_mmbtu  \
                                     75%          max               count
report_year
1994                            30.91000    45115.000              1235.0
1995                            29.79000     2396.770              1201.0
1996                            30.57250  7793482.000              1088.0
1997                            29.10400  7964521.000              1094.0
1998                            24.78000   270604.000              1107.0
1999                            26.12300     2891.100              1050.0
2000                            36.28800  1168000.000              1373.0
2001                            35.78250    34381.000              1356.0
2002                            31.96000    31416.000              1205.0
2003                            37.44100    34518.000              1211.0
2004                            45.84025   132884.000              1192.0
2005                            62.13000     8651.000              1269.0
2006                            68.49700     1431.000              1243.0
2007                            72.66500     4850.872              1264.0
2008                            80.97925    10490.000              1228.0
2009                            71.45950   730166.000              1222.0
2010                            86.36000    44033.320              1261.0
2011                            92.69675     9545.000              1240.0
2012                            99.53500    10129.000              1243.0
2013                            90.49000   135315.000              1199.0
2014                           103.24750   136410.000              1171.0
2015                            67.46000   140706.000              1093.0
2016                            54.04875    69440.000              1034.0
2017                            62.93000     3584.335               993.0
2018                            70.43900   245652.000               951.0

                                                                             \
                   mean           std     min       25%       50%       75%
report_year
1994           3.086977     13.120614  -3.003  1.389170  1.972000   3.00350
1995           2.868838     17.667516  -3.532  1.297000  1.702000   2.38057
1996           2.695880      2.810726 -41.501  1.297750  2.299500   3.35900
1997           3.113486      8.461000  -3.255  1.323913  2.549075   3.41300
1998           2.775862      8.652938  -3.781  1.223000  2.170000   2.74000
1999           2.740251      8.256836  -2.851  1.174000  2.271000   2.92725
2000           4.208403      9.485303  -8.906  1.332000  4.371000   5.60900
2001           4.612658      9.216095  -3.312  1.536750  4.540000   6.30025
2002           6.226281     73.048793  -3.541  1.489000  3.964000   5.61000
2003           7.223933     80.041595  -5.750  1.559500  5.740000   6.65700
2004           8.441597    101.732817  -2.484  1.683110  6.441500   7.57325
2005           9.397078     78.450850  -2.609  2.114000  8.180000  10.37800
2006          10.339898     85.879814  -2.076  2.379000  7.874000  12.16550
2007          10.735181     85.554339  -0.350  2.563250  7.835000  13.12625
2008          12.690115     86.902300  -0.280  2.867250  9.609500  15.23525
2009          10.619376     89.106481   0.433  3.036500  6.229000  13.10775
2010           8.551217      8.777441   0.071  3.416000  6.135000  14.58700
2011           9.237591      9.215246  -5.273  3.476000  5.636500  15.35250
2012           8.808904      8.189039   0.377  2.911500  4.181000  16.62500
2013           9.308225     10.547311   0.411  3.238000  4.905000  16.26200
2014          10.064673     12.030156   0.467  3.450500  5.788000  18.36000
2015           8.054361     12.562528   0.084  2.807000  3.996590  14.19300
2016           6.915613     13.338317  -0.416  2.661000  3.563500  10.33025
2017         368.736351  11401.124288   0.050  2.930000  3.880000  11.98500
2018           7.233643     10.704942   0.548  2.620000  3.714000  12.75500


                    max
report_year
1994            443.336
1995            605.294
1996             32.613
1997            265.497
1998            260.983
1999            242.886
2000            333.743
2001            327.194
2002           2536.971
2003           2788.180
2004           3515.924
2005           2797.354
2006           3030.015
2007           3043.388
2008           3044.916
2009           3115.812
2010            167.651
2011            137.959
2012             32.460
2013            241.533
2014            301.585
2015            351.058
2016            391.722
2017         359278.000
2018            273.821

[25 rows x 48 columns]

In [91]:
df.groupby('report_year')['fuel_cost_per_unit_burned'].max()

,count,mean,std,min,25%,50%,75%,max
report_year,,,,,,,,
1994,1235.0,2.724018e+06,8.204347e+06,2.0,28909.50,348464.0,1423604.00,89379732.0
1995,1201.0,3.712067e+06,2.140555e+07,4.0,58875.00,486812.0,1697176.00,555894250.0
1996,1088.0,2.544754e+06,7.060054e+06,8.0,35653.00,417474.0,1525624.25,85696171.0
1997,1094.0,2.813503e+06,7.634741e+06,9.0,39165.00,466028.5,1743504.75,78247532.0
1998,1107.0,3.267453e+06,8.311974e+06,1.0,137587.50,711532.0,2211402.50,91579544.0
1999,1050.0,3.281281e+06,8.410643e+06,2.0,156741.00,733709.5,2299509.50,93897480.0
2000,1373.0,2.472032e+06,7.451205e+06,1.0,17815.00,287280.0,1496644.00,92841713.0
2001,1356.0,2.321402e+06,6.885377e+06,1.0,13806.75,191776.0,1354828.75,80734639.0
2002,1205.0,2.145645e+06,7.099854e+06,1.0,9830.00,215450.0,1316877.00,120183976.0
2003,1211.0,1.888622e+06,6.624766e+06,2.0,7836.50,137174.0,1145717.00,88459420.0
2004,1192.0,1.782547e+06,8.161217e+06,1.0,7269.25,100256.5,995326.75,198577395.0
2005,1269.0,1.768876e+06,5.781958e+06,1.0,9784.00,132860.0,1249569.00,91621163.0
2006,1243.0,1.957264e+06,7.200749e+06,1.0,8152.00,140013.0,1149645.50,133220134.0
2007,1264.0,2.035696e+06,6.435263e+06,1.0,9079.50,165427.5,1330981.50,83812266.0
2008,1228.0,2.046455e+06,6.602461e+06,1.0,8283.25,141690.5,1144645.00,76417286.0
2009,1222.0,2.154993e+06,7.016638e+06,1.0,7994.50,115548.0,1027860.75,79380300.0
2010,1261.0,2.423720e+06,7.816911e+06,1.0,8929.00,131761.0,1171692.00,94254109.0
2011,1240.0,2.461332e+06,8.332992e+06,2.0,8514.25,159573.0,1190183.75,137183568.0
2012,1243.0,2.747094e+06,9.454088e+06,1.0,7929.50,151344.0,1167398.50,166385450.0
2013,1199.0,2.741505e+06,9.341617e+06,1.0,8682.00,174355.0,1239883.50,147837343.0
2014,1171.0,2.700008e+06,9.044107e+06,2.0,10043.00,171852.0,1163889.00,135885298.0
2015,1093.0,3.340131e+06,1.052145e+07,4.0,11813.00,222311.0,1492491.00,139004631.0
2016,1034.0,3.693289e+06,1.090596e+07,2.0,10937.75,253766.5,1719714.00,142140958.0
2017,993.0,3.352850e+06,9.770784e+06,1.0,9569.00,251442.0,1621855.00,110018100.0
2018,951.0,4.178890e+06,1.135144e+07,3.0,19239.00,372264.0,2344232.00,137994128.0

In [103]:
df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].pct_change()

0             NaN
1       -0.000538
2        1.137783
3        0.188570
4             NaN
           ...
29518   -0.426170
29519   -0.236402
29520    0.306849
29521   -0.776479
29522   -1.000000
Name: fuel_cost_per_unit_burned, Length: 29523, dtype: float64